### ISSUE TITLE
What shall we call this APP?

### ISSUE THREAD

**Issue by drewdeal** [devopsdojoconsortium/TeamVSMs#1]
The original TeamVSMs repo name is BEGGING for a fix... intentionally.
There are a few ideas being floated with friends already, and a bunch of deliberation around a couple. But it pays to break things down and help the conversation track to a great name. There are three buckets:

### enGauge
This looks to win for use at one Enterprise. They (unnamed at present) need an intake system for the DevOps transformation team for myriad Engagement types (Dojos, SRE's, VSM, training, etc).
The focus on Engagements is a winner for the name. EnGauge serves the idea of bringing groups (programs/teams/leadership) in to 'engage' with coaching or similar DevOps expertise.

The downside of the name is that 'Guage' also great as a measurement inference is oddly archaic as a term in digital domains. Also, confusing to pronounce by international folk.

### Kaizenic 
This one is fancied by Drew (founder) and it seems the fact that it is an adjective, (rarely used for brands) may not hurt. It is descriptive and Lean is at the heart of the app. One millennial hated it for some reason, thinking like a drug name?
(KaizenIt is great too, but there is an [Event company](https://www.kaizenitservices.com/) filling that spot it appears)

## 2) Names that indicate/infer the purpose of connecting teams/programs with coaching engagements. 
Play with these keywords (or make up your own) to create compound words to make a name up:
### Subjects (or qualifier)
- Team
- Coach
- Connections
- Learn
- Kaizen

### Objects (suffix or place)
- Connect
- Scape
- Trek
- Space
- Ops
- Stream
- ica

### Areté
It means, "The Quality of Excellence" (purpose, virtue - to fulfill purpose)
https://en.wikipedia.org/wiki/Arete
https://youtu.be/hktDNGcsRfs

### Apachos
Greek for Lean.
Connotes 'epoch', 'destiny' a bit.

**Comment by chrisgallivan** [comment]
Breaking Bottlenecks

**Comment by chrisgallivan** [comment]
Sensei-tional

**Comment by chrisgallivan** [comment]
Team Charter

**Comment by drewdeal** [comment]
Been hearing FLOW from a consortium member.... 
Also, Engagement is emerging as a key word as well, as the actual team object is really an engagement object... a team can do more than one dojo or other trackable coaching shtick (ie engagement)

**Comment by chrisgallivan** [comment]
Murmuration

**Comment by drewdeal** [comment]
Ok.. finally... resting on this decision I feel has paid off.
The name shall be called TeamAssist.
It is unique on npm, github and google... all good

As I told my friend Brian, who was very helpful a while back in brainstorming a name....
> **"[the name] covers the function of it at right depth... unique enough in language and brand"**
